-- require 'user.override.user.plugins'
require 'user.override.user.mapleader'
require 'user.override.user.alpha'
require 'user.override.user.harpoon'
require 'user.override.user.luasnip'
require 'user.override.user.keymap'
require 'user.override.user.autocommands'
require 'user.override.user.filetypes'
vim.opt.mouse='a'
